WINDOW_TITLE  = "Computational Biology Final Project: Genetic Algorithm | Made by Alexander L. Myfia & Aldika F. Reynanda"
WINDOW_WIDTH  = 1920
WINDOW_HEIGHT = 1080
WINDOW_ICON   = "app-icon.png"

DEFAULT_POPULATION_SIZE = 10
DEFAULT_MAX_GEN = 100
DEFAULT_ELITE_CARRYOVER = 1
DEFAULT_MUTATION_PROBABILITY = 5

INTERFACE_BG_COL = (200,200,200)
MOTIF_LENGTH = 120
GENE_DISPLAY_TEXT_SIZE = 15
CONNECTION_LINE_THICKNESS = 3
PROGRESSION_DELAY_MS = 50
DEFAULT_DATASET = 'ecoli'